export const user = {
  id: 1,
  name: 'Admin Admin',
  email: 'admin@admin.com',
  email_verified_at: null,
  disabled: false,
  phoneNumber: null,
  uid: null,
  role_id: 1,
  country_id: 194,
  region_id: 3224,
  city_id: 2317348,
  token: '1|H4tnpT12gT77yMYAPz7Z9B3ALoaXBW1QkhLkJsnE',
  person: {
    id: 1,
    firstName: 'Admin Admin',
    lastName: 'Admin Admin',
    cellPhone: null,
    birthDate: null,
    address: null,
    neighborhood: null,
    user_id: 1,
  },
  photo: {
    entity_id: 1,
    id: -1,
    name: 'logo.png',
    field: 'photo',
    entity: 'auth_users',
    extension: 'png',
    publicPath: '/storage/assets/images/logo.png',
  },
  roles: [
    {
      id: 1,
      name: 'Administrador',
      description: 'Administrador',
      pivot: {
        user_id: 1,
        role_id: 1,
      },
      menus: [
        {
          id: 2,
          icon: 'tools',
          name: 'Sistema',
          urlBackEnd: 'api.#system#.index',
          urlFrontEnd: '/#system#',
          isSection: true,
          isVisible: true,
          orderInMenu: 1,
          permission_id: 0,
          created_by: null,
          updated_by: null,
          subMenus: [
            {
              id: 6,
              icon: 'address-book',
              name: 'Usuarios',
              urlBackEnd: 'api.users.index',
              urlFrontEnd: '/users',
              isSection: false,
              isVisible: true,
              orderInMenu: 0,
              permission_id: 2,
              created_by: null,
              updated_by: null,
              pivot: {
                role_id: 1,
                permission_id: 6,
              },
            },
            {
              id: 11,
              icon: 'fingerprint',
              name: 'Roles',
              urlBackEnd: 'api.roles.index',
              urlFrontEnd: '/roles',
              isSection: false,
              isVisible: true,
              orderInMenu: 1,
              permission_id: 2,
              created_by: null,
              updated_by: null,
              pivot: {
                role_id: 1,
                permission_id: 11,
              },
            },
          ],
          pivot: {
            role_id: 1,
            permission_id: 2,
          },
        },
        {
          id: 3,
          icon: 'users-cog',
          name: 'Clientes',
          urlBackEnd: 'api.#accounts#.index',
          urlFrontEnd: '/#accounts#',
          isSection: true,
          isVisible: true,
          orderInMenu: 2,
          permission_id: 0,
          created_by: null,
          updated_by: null,
          subMenus: [
            {
              id: 16,
              icon: 'address-book',
              name: 'Cuentas',
              urlBackEnd: 'api.accounts.index',
              urlFrontEnd: '/accounts',
              isSection: false,
              isVisible: true,
              orderInMenu: 0,
              permission_id: 3,
              created_by: null,
              updated_by: null,
              pivot: {
                role_id: 1,
                permission_id: 16,
              },
            },
          ],
          pivot: {
            role_id: 1,
            permission_id: 3,
          },
        },
        {
          id: 4,
          icon: 'globe',
          name: 'Países',
          urlBackEnd: 'api.#countries#.index',
          urlFrontEnd: '/#countries#',
          isSection: true,
          isVisible: true,
          orderInMenu: 3,
          permission_id: 0,
          created_by: null,
          updated_by: null,
          subMenus: [
            {
              id: 21,
              icon: 'flag',
              name: 'Países',
              urlBackEnd: 'api.countries.index',
              urlFrontEnd: '/countries',
              isSection: false,
              isVisible: true,
              orderInMenu: 0,
              permission_id: 4,
              created_by: null,
              updated_by: null,
              pivot: {
                role_id: 1,
                permission_id: 21,
              },
            },
            {
              id: 26,
              icon: 'globe-americas',
              name: 'Regiones',
              urlBackEnd: 'api.regions.index',
              urlFrontEnd: '/regions',
              isSection: false,
              isVisible: true,
              orderInMenu: 1,
              permission_id: 4,
              created_by: null,
              updated_by: null,
              pivot: {
                role_id: 1,
                permission_id: 26,
              },
            },
            {
              id: 31,
              icon: 'city',
              name: 'Ciudades',
              urlBackEnd: 'api.cities.index',
              urlFrontEnd: '/cities',
              isSection: false,
              isVisible: true,
              orderInMenu: 2,
              permission_id: 4,
              created_by: null,
              updated_by: null,
              pivot: {
                role_id: 1,
                permission_id: 31,
              },
            },
          ],
          pivot: {
            role_id: 1,
            permission_id: 4,
          },
        },
      ],
      urlPermissions: [
        'files.upload',
        '/users/show',
        '/users/new',
        '/users/edit',
        '/users/delete',
        '/users',
        '/roles/show',
        '/roles/new',
        '/roles/edit',
        '/roles/delete',
        '/roles',
        '/regions/show',
        '/regions/new',
        '/regions/edit',
        '/regions/delete',
        '/regions',
        '/countries/show',
        '/countries/new',
        '/countries/edit',
        '/countries/delete',
        '/countries',
        '/cities/show',
        '/cities/new',
        '/cities/edit',
        '/cities/delete',
        '/cities',
        '/accounts/show',
        '/accounts/new',
        '/accounts/edit',
        '/accounts/delete',
        '/accounts',
        '/#system#',
        '/#misc-hide#',
        '/#countries#',
        '/#accounts#',
        '/dashboard',
        '/not-authorized',
        '/not-found',
      ],
    },
    {
      id: 2,
      name: 'Sub Administrador',
      description: 'Sub Administrador',
      pivot: {
        user_id: 1,
        role_id: 2,
      },
      menus: [],
      urlPermissions: [],
    },
  ],
  role: {
    id: 1,
    name: 'Administrador',
    description: 'Administrador',
    pivot: {
      user_id: 1,
      role_id: 1,
    },
    menus: [
      {
        id: 2,
        icon: 'tools',
        name: 'Sistema',
        urlBackEnd: 'api.#system#.index',
        urlFrontEnd: '/#system#',
        isSection: true,
        isVisible: true,
        orderInMenu: 1,
        permission_id: 0,
        created_by: null,
        updated_by: null,
        subMenus: [
          {
            id: 6,
            icon: 'address-book',
            name: 'Usuarios',
            urlBackEnd: 'api.users.index',
            urlFrontEnd: '/users',
            isSection: false,
            isVisible: true,
            orderInMenu: 0,
            permission_id: 2,
            created_by: null,
            updated_by: null,
            pivot: {
              role_id: 1,
              permission_id: 6,
            },
          },
          {
            id: 11,
            icon: 'fingerprint',
            name: 'Roles',
            urlBackEnd: 'api.roles.index',
            urlFrontEnd: '/roles',
            isSection: false,
            isVisible: true,
            orderInMenu: 1,
            permission_id: 2,
            created_by: null,
            updated_by: null,
            pivot: {
              role_id: 1,
              permission_id: 11,
            },
          },
        ],
        pivot: {
          role_id: 1,
          permission_id: 2,
        },
      },
      {
        id: 3,
        icon: 'users-cog',
        name: 'Clientes',
        urlBackEnd: 'api.#accounts#.index',
        urlFrontEnd: '/#accounts#',
        isSection: true,
        isVisible: true,
        orderInMenu: 2,
        permission_id: 0,
        created_by: null,
        updated_by: null,
        subMenus: [
          {
            id: 16,
            icon: 'address-book',
            name: 'Cuentas',
            urlBackEnd: 'api.accounts.index',
            urlFrontEnd: '/accounts',
            isSection: false,
            isVisible: true,
            orderInMenu: 0,
            permission_id: 3,
            created_by: null,
            updated_by: null,
            pivot: {
              role_id: 1,
              permission_id: 16,
            },
          },
        ],
        pivot: {
          role_id: 1,
          permission_id: 3,
        },
      },
      {
        id: 4,
        icon: 'globe',
        name: 'Países',
        urlBackEnd: 'api.#countries#.index',
        urlFrontEnd: '/#countries#',
        isSection: true,
        isVisible: true,
        orderInMenu: 3,
        permission_id: 0,
        created_by: null,
        updated_by: null,
        subMenus: [
          {
            id: 21,
            icon: 'flag',
            name: 'Países',
            urlBackEnd: 'api.countries.index',
            urlFrontEnd: '/countries',
            isSection: false,
            isVisible: true,
            orderInMenu: 0,
            permission_id: 4,
            created_by: null,
            updated_by: null,
            pivot: {
              role_id: 1,
              permission_id: 21,
            },
          },
          {
            id: 26,
            icon: 'globe-americas',
            name: 'Regiones',
            urlBackEnd: 'api.regions.index',
            urlFrontEnd: '/regions',
            isSection: false,
            isVisible: true,
            orderInMenu: 1,
            permission_id: 4,
            created_by: null,
            updated_by: null,
            pivot: {
              role_id: 1,
              permission_id: 26,
            },
          },
          {
            id: 31,
            icon: 'city',
            name: 'Ciudades',
            urlBackEnd: 'api.cities.index',
            urlFrontEnd: '/cities',
            isSection: false,
            isVisible: true,
            orderInMenu: 2,
            permission_id: 4,
            created_by: null,
            updated_by: null,
            pivot: {
              role_id: 1,
              permission_id: 31,
            },
          },
        ],
        pivot: {
          role_id: 1,
          permission_id: 4,
        },
      },
    ],
    urlPermissions: [
      'files.upload',
      '/users/show',
      '/users/new',
      '/users/edit',
      '/users/delete',
      '/users',
      '/roles/show',
      '/roles/new',
      '/roles/edit',
      '/roles/delete',
      '/roles',
      '/regions/show',
      '/regions/new',
      '/regions/edit',
      '/regions/delete',
      '/regions',
      '/countries/show',
      '/countries/new',
      '/countries/edit',
      '/countries/delete',
      '/countries',
      '/cities/show',
      '/cities/new',
      '/cities/edit',
      '/cities/delete',
      '/cities',
      '/accounts/show',
      '/accounts/new',
      '/accounts/edit',
      '/accounts/delete',
      '/accounts',
      '/#system#',
      '/#misc-hide#',
      '/#countries#',
      '/#accounts#',
      '/dashboard',
      '/not-authorized',
      '/not-found',
    ],
  },
}
