export const l: any = {
  misc: {
    csv: '/assets/images/admin/ic-csv.svg',
    zip: '/assets/images/admin/ic-zip.svg',
    pdf: '/assets/images/admin/ic-pdf.svg',
    upload: '/assets/images/admin/ic-upload.svg',
    loading: '/assets/images/admin/ic-loading.svg',
    pageLimit: [
      {c: '5', v: 5},
      {c: '10', v: 10},
      {c: '50', v: 50},
      {c: '100', v: 100},
      {c: '1,000', v: 1000},
      {c: '10,000', v: 10000},
    ],
    slug: {
      name: '',
      label: 'Slug',
      field: 'stores.slug',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      fixed: false,
      sorting: true,
      alias: '',
      model: '',
    },
  },
  msg: {
    error: 'Ha ocurrido un error',
    success: 'Operaci\u00f3n realizada con \u00e9xito',
    warning: 'Atenci\u00f3n',
    info: 'Informaci\u00f3n',
    confirm: 'Confirmar',
    confirmDelete: '\u00bfEst\u00e1 seguro de eliminar este registro?',
    confirmDeleteMany: '\u00bfEst\u00e1 seguro de eliminar los registros seleccionados?',
    confirmDeleteManyRows: '\u00bfEst\u00e1 seguro de eliminar los registros seleccionados?',
    noData: 'No hay datos para mostrar',
  },
  user: {
    tablePK: 'id',
    tableName: 'auth_users',
    ownName: 'Usuario',
    ownNamePlural: 'Usuarios',
    id: {
      name: 'id',
      label: '#',
      field: 'auth_users.id',
      type: 'pk',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    name: {
      name: 'name',
      label: 'Nombre',
      field: 'auth_users.name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    email: {
      name: 'email',
      label: 'Correo electr\u00f3nico',
      field: 'auth_users.email',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    password: {
      name: 'password',
      label: 'Contrase\u00f1a',
      field: 'auth_users.password',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    email_verified_at: {
      name: 'email_verified_at',
      label: 'Email_Verified_At',
      field: 'auth_users.email_verified_at',
      type: 'date',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    disabled: {
      name: 'disabled',
      label: 'Deshabilitado',
      field: 'auth_users.disabled',
      type: 'boolean',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    phoneNumber: {
      name: 'phoneNumber',
      label: 'Tel\u00e9fono',
      field: 'auth_users.phoneNumber',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    uid: {
      name: 'uid',
      label: 'Uid',
      field: 'auth_users.uid',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    role_id: {
      name: 'role_id',
      label: 'Role_Id',
      field: 'auth_users.role_id',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    country_id: {
      name: 'country_id',
      label: 'Country_Id',
      field: 'auth_users.country_id',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    region_id: {
      name: 'region_id',
      label: 'Region_Id',
      field: 'auth_users.region_id',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    city_id: {
      name: 'city_id',
      label: 'City_Id',
      field: 'auth_users.city_id',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    remember_token: {
      name: 'remember_token',
      label: 'Remember_Token',
      field: 'auth_users.remember_token',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    countryName: {
      name: 'countryName',
      label: 'Pa\u00eds',
      field: 'countryName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    regionName: {
      name: 'regionName',
      label: 'Region',
      field: 'regionName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    cityName: {
      name: 'cityName',
      label: 'Ciudad',
      field: 'cityName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    roleName: {
      name: 'roleName',
      label: 'Role',
      field: 'roleName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    person: {
      name: 'person',
      label: 'Person',
      field: 'personName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    account: {
      name: 'account',
      label: 'Account',
      field: 'accountName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    roles: {
      name: 'roles',
      label: 'Roles',
      field: 'role.id',
      type: 'projection',
      allowSearch: true,
      allowExport: false,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
    photo: {
      name: 'photo',
      label: 'Foto',
      field: 'photo',
      type: 'projection',
      allowSearch: true,
      allowExport: false,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'user',
    },
  },
  role: {
    tablePK: 'id',
    tableName: 'auth_roles',
    ownName: 'Rol',
    ownNamePlural: 'Roles',
    id: {
      name: 'id',
      label: '#',
      field: 'auth_roles.id',
      type: 'pk',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'role',
    },
    name: {
      name: 'name',
      label: 'Nombre',
      field: 'auth_roles.name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'role',
    },
    description: {
      name: 'description',
      label: 'Descripci\u00f3n',
      field: 'auth_roles.description',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'role',
    },
    permissions: {
      name: 'permissions',
      label: 'Permission #',
      field: 'permission.id',
      type: 'number',
      allowSearch: true,
      allowExport: false,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'role',
    },
    permissionName: {
      name: 'permissionName',
      label: 'Permission',
      field: 'permissionName',
      type: 'string',
      allowSearch: true,
      allowExport: false,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'role',
    },
  },
  permission: {
    tablePK: 'id',
    tableName: 'auth_permissions',
    ownName: 'Permiso',
    ownNamePlural: 'Permisos',
    '': {
      name: '',
      label: 'Order In Menu',
      field: 'auth_permissions.orderInMenu',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'permission',
    },
  },
  person: {
    tablePK: 'id',
    tableName: 'auth_people',
    ownName: 'Personal',
    ownNamePlural: 'Personal',
    id: {
      name: 'id',
      label: '#',
      field: 'auth_people.id',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'person',
    },
    firstName: {
      name: 'firstName',
      label: 'Nombre',
      field: 'auth_people.firstName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'person',
    },
    lastName: {
      name: 'lastName',
      label: 'Apellido',
      field: 'auth_people.lastName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'person',
    },
    cellPhone: {
      name: 'cellPhone',
      label: 'Tel\u00e9fono',
      field: 'auth_people.cellPhone',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'person',
    },
    birthDate: {
      name: 'birthDate',
      label: 'Fecha de nacimiento',
      field: 'auth_people.birthDate',
      type: 'date',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'person',
    },
    address: {
      name: 'address',
      label: 'Direcci\u00f3n',
      field: 'auth_people.address',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'person',
    },
    neighborhood: {
      name: 'neighborhood',
      label: 'Vecindario',
      field: 'auth_people.neighborhood',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'person',
    },
    userName: {
      name: 'userName',
      label: 'User',
      field: 'userName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'person',
    },
  },
  account: {
    tablePK: 'id',
    tableName: 'auth_accounts',
    ownName: 'Contacto',
    ownNamePlural: 'Contactos',
    id: {
      name: 'id',
      label: '#',
      field: 'auth_accounts.id',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'account',
    },
    firstName: {
      name: 'firstName',
      label: 'Nombre',
      field: 'auth_accounts.firstName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'account',
    },
    lastName: {
      name: 'lastName',
      label: 'Apellido',
      field: 'auth_accounts.lastName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'account',
    },
    cellPhone: {
      name: 'cellPhone',
      label: 'Tel\u00e9fono',
      field: 'auth_accounts.cellPhone',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'account',
    },
    birthDate: {
      name: 'birthDate',
      label: 'Cumplea\u00f1os',
      field: 'auth_accounts.birthDate',
      type: 'date',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'account',
    },
    address: {
      name: 'address',
      label: 'Direcci\u00f3n',
      field: 'auth_accounts.address',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'account',
    },
    neighborhood: {
      name: 'neighborhood',
      label: 'Vecindario',
      field: 'auth_accounts.neighborhood',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'account',
    },
    userName: {
      name: 'userName',
      label: 'User',
      field: 'userName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'account',
    },
  },
  visorLogError: {
    tablePK: 'id',
    tableName: 'visor_log_errors',
    ownName: 'Visualizaci\u00f3n de error',
    ownNamePlural: 'Visualizaci\u00f3n de errores',
    id: {
      name: 'id',
      label: '#',
      field: 'visor_log_errors.id',
      type: 'pk',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'visorLogError',
    },
    payload: {
      name: 'payload',
      label: 'Fallo',
      field: 'visor_log_errors.payload',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'visorLogError',
    },
    error: {
      name: 'error',
      label: 'Fallo',
      field: 'visor_log_errors.payload',
      type: 'projection',
      allowSearch: true,
      allowExport: false,
      allowImport: false,
      allowInList: true,
      sorting: false,
      fixed: false,
      model: 'visorLogError',
    },
    queue: {
      name: 'queue',
      label: 'Proceso',
      field: 'visor_log_errors.queue',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'visorLogError',
    },
    container_id: {
      name: 'container_id',
      label: '[id]',
      field: 'visor_log_errors.container_id',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'visorLogError',
    },
    created_at: {
      name: 'created_at',
      label: 'Fecha',
      field: 'visor_log_errors.created_at',
      type: 'date-time',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'visorLogError',
    },
  },
  country: {
    tablePK: 'id',
    tableName: 'countries',
    ownName: 'Pa\u00eds',
    ownNamePlural: 'Pa\u00edses',
    id: {
      name: 'id',
      label: '#',
      field: 'countries.id',
      type: 'pk',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'country',
    },
    name: {
      name: 'name',
      label: 'Nombre',
      field: 'countries.name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'country',
    },
    code: {
      name: 'code',
      label: 'C\u00f3digo',
      field: 'countries.code',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'country',
    },
  },
  region: {
    tablePK: 'id',
    tableName: 'regions',
    ownName: 'Departamento/Provincia',
    ownNamePlural: 'Departamentos/Provincias',
    id: {
      name: 'id',
      label: '#',
      field: 'regions.id',
      type: 'pk',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'region',
    },
    name: {
      name: 'name',
      label: 'Nombre',
      field: 'regions.name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'region',
    },
    code: {
      name: 'code',
      label: 'C\u00f3digo',
      field: 'regions.code',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'region',
    },
    country_id: {
      name: 'country_id',
      label: 'Country_Id',
      field: 'regions.country_id',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'region',
    },
    countryName: {
      name: 'countryName',
      label: 'Pa\u00eds',
      field: 'countryName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'region',
    },
  },
  city: {
    tablePK: 'id',
    tableName: 'cities',
    ownName: 'Ciudad',
    ownNamePlural: 'Ciudades',
    id: {
      name: 'id',
      label: '#',
      field: 'cities.id',
      type: 'pk',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'city',
    },
    name: {
      name: 'name',
      label: 'Nombre',
      field: 'cities.name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'city',
    },
    latitude: {
      name: 'latitude',
      label: 'Latitud',
      field: 'cities.latitude',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'city',
    },
    longitude: {
      name: 'longitude',
      label: 'Longitud',
      field: 'cities.longitude',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'city',
    },
    country_id: {
      name: 'country_id',
      label: 'Pa\u00eds #',
      field: 'cities.country_id',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'city',
    },
    region_id: {
      name: 'region_id',
      label: 'Region #',
      field: 'cities.region_id',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'city',
    },
    countryName: {
      name: 'countryName',
      label: 'Pa\u00eds',
      field: 'countryName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'city',
    },
    regionName: {
      name: 'regionName',
      label: 'Region',
      field: 'regionName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      sorting: true,
      fixed: false,
      model: 'city',
    },
  },
}
