import {DBType} from 'base-cms' // from '@juanfv2/base-cms';

export const l = {
  k: {} as any,

  isObject: (value: any) => typeof value === 'object' && value !== null && !Array.isArray(value),

  getDBFields: (values: any): DBType[] => {
    const labels = []
    for (let key1 in values) {
      const model = values[key1]
      if (l.isObject(model)) {
        labels.push(model)
      }
    }
    return labels
  },

  getLabels: (values: any) => {
    const labels = []
    for (let key1 in values) {
      const model = values[key1]
      if (l.isObject(model)) {
        let _index = 0
        for (let key2 in model) {
          const field = model[key2]
          if (l.isObject(field)) {
            field.model = key1
            field.index = _index
            labels.push(field)
            _index++
          }
        }
      }
    }
    return labels
  },
  misc: {
    csv: '/assets/images/admin/ic-csv.svg',
    zip: '/assets/images/admin/ic-zip.svg',
    pdf: '/assets/images/admin/ic-pdf.svg',
    upload: '/assets/images/admin/ic-upload.svg',
    loading: '/assets/images/admin/ic-loading.svg',
    pageLimit: [
      {c: '5', v: 5},
      {c: '10', v: 10},
      {c: '50', v: 50},
      {c: '100', v: 100},
      {c: '1,000', v: 1000},
      {c: '10,000', v: 10000},
    ],
    slug: {
      name: 'slug',
      label: 'Slug',
      field: 'stores.slug',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
  },
  msg: {
    error: 'Ha ocurrido un error',
    success: 'Operaci\u00f3n realizada con \u00e9xito',
    warning: 'Atenci\u00f3n',
    info: 'Informaci\u00f3n',
    confirm: 'Confirmar',
    confirmDelete: '\u00bfEst\u00e1 seguro de eliminar este registro?',
    confirmDeleteMany: '\u00bfEst\u00e1 seguro de eliminar los registros seleccionados?',
    confirmDeleteManyRows: '\u00bfEst\u00e1 seguro de eliminar los registros seleccionados?',
    noData: 'No hay datos para mostrar',
  },
  user: {
    tablePK: 'id',
    tableName: 'auth_users',
    ownName: 'Usuario',
    ownNamePlural: 'Usuarios',
    id: {
      name: 'id',
      label: '#',
      field: 'auth_users.id',
      type: 'pk',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    name: {
      name: 'name',
      label: 'Nombre',
      field: 'auth_users.name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    email: {
      name: 'email',
      label: 'Correo electr\u00f3nico',
      field: 'auth_users.email',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    password: {
      name: 'password',
      label: 'Contrase\u00f1a',
      field: 'auth_users.password',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: true,
      sorting: true,
      fixed: false,
    } as DBType,
    email_verified_at: {
      name: 'email_verified_at',
      label: 'Email_Verified_At',
      field: 'auth_users.email_verified_at',
      type: 'date',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: true,
      sorting: true,
      fixed: false,
    } as DBType,
    disabled: {
      name: 'disabled',
      label: 'Deshabilitado',
      field: 'auth_users.disabled',
      type: 'boolean',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    phoneNumber: {
      name: 'phoneNumber',
      label: 'Tel\u00e9fono',
      field: 'auth_users.phoneNumber',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    uid: {
      name: 'uid',
      label: 'Uid',
      field: 'auth_users.uid',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: true,
      sorting: true,
      fixed: false,
    } as DBType,
    role_id: {
      name: 'role_id',
      label: 'Rol #',
      field: 'auth_users.role_id',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: false,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    country_id: {
      name: 'country_id',
      label: 'Pa\u00eds #',
      field: 'auth_users.country_id',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: false,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    region_id: {
      name: 'region_id',
      label: 'Region #',
      field: 'auth_users.region_id',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: false,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    city_id: {
      name: 'city_id',
      label: 'Ciudad #',
      field: 'auth_users.city_id',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: false,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    remember_token: {
      name: 'remember_token',
      label: 'Remember_Token',
      field: 'auth_users.remember_token',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: false,
      hidden: true,
      sorting: true,
      fixed: false,
    } as DBType,
    countryName: {
      name: 'countryName',
      label: 'Pa\u00eds',
      field: 'countryName',
      type: 'string',
      allowSearch: false,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    regionName: {
      name: 'regionName',
      label: 'Region',
      field: 'regionName',
      type: 'string',
      allowSearch: false,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    cityName: {
      name: 'cityName',
      label: 'Ciudad',
      field: 'cityName',
      type: 'string',
      allowSearch: false,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    roleName: {
      name: 'roleName',
      label: 'Rol',
      field: 'roleName',
      type: 'string',
      allowSearch: false,
      allowExport: true,
      allowImport: false,
      allowInList: false,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    person: {
      name: 'person',
      label: 'Person',
      field: 'personName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: false,
      hidden: true,
      sorting: true,
      fixed: false,
    } as DBType,
    account: {
      name: 'account',
      label: 'Account',
      field: 'accountName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: false,
      hidden: true,
      sorting: true,
      fixed: false,
    } as DBType,
    roles: {
      name: 'roles',
      label: 'Roles',
      field: 'role.id',
      type: 'projection',
      allowSearch: false,
      allowExport: false,
      allowImport: false,
      allowInList: true,
      hidden: false,
      sorting: false,
      fixed: false,
    } as DBType,
    photo: {
      name: 'photo',
      label: 'Foto',
      field: 'photo',
      type: 'projection',
      allowSearch: false,
      allowExport: false,
      allowImport: false,
      allowInList: true,
      hidden: false,
      sorting: false,
      fixed: false,
    } as DBType,
  },
  role: {
    tablePK: 'id',
    tableName: 'auth_roles',
    ownName: 'Rol',
    ownNamePlural: 'Roles',
    id: {
      name: 'id',
      label: '#',
      field: 'auth_roles.id',
      type: 'pk',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    name: {
      name: 'name',
      label: 'Nombre',
      field: 'auth_roles.name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    description: {
      name: 'description',
      label: 'Descripci\u00f3n',
      field: 'auth_roles.description',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    permissions: {
      name: 'permissions',
      label: 'Permission #',
      field: 'permission.id',
      type: 'number',
      allowSearch: true,
      allowExport: false,
      allowImport: false,
      allowInList: true,
      hidden: true,
      sorting: true,
      fixed: false,
    } as DBType,
    permissionName: {
      name: 'permissionName',
      label: 'Permission',
      field: 'permissionName',
      type: 'string',
      allowSearch: true,
      allowExport: false,
      allowImport: false,
      allowInList: true,
      hidden: true,
      sorting: true,
      fixed: false,
    } as DBType,
  },
  permission: {
    tablePK: 'id',
    tableName: 'auth_permissions',
    ownName: 'Permiso',
    ownNamePlural: 'Permisos',
    orderInMenu: {
      name: 'orderInMenu',
      label: 'Order In Menu',
      field: 'auth_permissions.orderInMenu',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
  },
  person: {
    tablePK: 'id',
    tableName: 'auth_people',
    ownName: 'Personal',
    ownNamePlural: 'Personal',
    id: {
      name: 'id',
      label: '#',
      field: 'auth_people.id',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    first_name: {
      name: 'first_name',
      label: 'Nombre',
      field: 'auth_people.first_name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    last_name: {
      name: 'last_name',
      label: 'Apellido',
      field: 'auth_people.last_name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    cell_phone: {
      name: 'cell_phone',
      label: 'Tel\u00e9fono',
      field: 'auth_people.cell_phone',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    birth_date: {
      name: 'birth_date',
      label: 'Fecha de nacimiento',
      field: 'auth_people.birth_date',
      type: 'date',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    address: {
      name: 'address',
      label: 'Direcci\u00f3n',
      field: 'auth_people.address',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    neighborhood: {
      name: 'neighborhood',
      label: 'Vecindario',
      field: 'auth_people.neighborhood',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    userName: {
      name: 'userName',
      label: 'User',
      field: 'userName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
  },
  account: {
    tablePK: 'id',
    tableName: 'auth_accounts',
    ownName: 'Contacto',
    ownNamePlural: 'Contactos',
    id: {
      name: 'id',
      label: '#',
      field: 'auth_accounts.id',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    first_name: {
      name: 'first_name',
      label: 'Nombre',
      field: 'auth_accounts.first_name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    last_name: {
      name: 'last_name',
      label: 'Apellido',
      field: 'auth_accounts.last_name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    cell_phone: {
      name: 'cell_phone',
      label: 'Tel\u00e9fono',
      field: 'auth_accounts.cell_phone',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    birth_date: {
      name: 'birth_date',
      label: 'Cumplea\u00f1os',
      field: 'auth_accounts.birth_date',
      type: 'date',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    address: {
      name: 'address',
      label: 'Direcci\u00f3n',
      field: 'auth_accounts.address',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    neighborhood: {
      name: 'neighborhood',
      label: 'Vecindario',
      field: 'auth_accounts.neighborhood',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    userName: {
      name: 'userName',
      label: 'User',
      field: 'userName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
  },
  visorLogError: {
    tablePK: 'id',
    tableName: 'visor_log_errors',
    ownName: 'Visualizaci\u00f3n de error',
    ownNamePlural: 'Visualizaci\u00f3n de errores',
    id: {
      name: 'id',
      label: '#',
      field: 'visor_log_errors.id',
      type: 'pk',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    payload: {
      name: 'payload',
      label: 'Fallo',
      field: 'visor_log_errors.payload',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    error: {
      name: 'error',
      label: 'Fallo',
      field: 'visor_log_errors.payload',
      type: 'projection',
      allowSearch: true,
      allowExport: false,
      allowImport: false,
      allowInList: true,
      hidden: false,
      sorting: false,
      fixed: false,
    } as DBType,
    queue: {
      name: 'queue',
      label: 'Proceso',
      field: 'visor_log_errors.queue',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    container_id: {
      name: 'container_id',
      label: '[id]',
      field: 'visor_log_errors.container_id',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    created_at: {
      name: 'created_at',
      label: 'Fecha',
      field: 'visor_log_errors.created_at',
      type: 'date-time',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
  },
  country: {
    tablePK: 'id',
    tableName: 'countries',
    ownName: 'Pa\u00eds',
    ownNamePlural: 'Pa\u00edses',
    id: {
      name: 'id',
      label: '#',
      field: 'countries.id',
      type: 'pk',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    name: {
      name: 'name',
      label: 'Nombre',
      field: 'countries.name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    code: {
      name: 'code',
      label: 'C\u00f3digo',
      field: 'countries.code',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
  },
  region: {
    tablePK: 'id',
    tableName: 'regions',
    ownName: 'Departamento/Provincia',
    ownNamePlural: 'Departamentos/Provincias',
    id: {
      name: 'id',
      label: '#',
      field: 'regions.id',
      type: 'pk',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    name: {
      name: 'name',
      label: 'Nombre',
      field: 'regions.name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    code: {
      name: 'code',
      label: 'C\u00f3digo',
      field: 'regions.code',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    country_id: {
      name: 'country_id',
      label: 'Country_Id',
      field: 'regions.country_id',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    countryName: {
      name: 'countryName',
      label: 'Pa\u00eds',
      field: 'countryName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
  },
  city: {
    tablePK: 'id',
    tableName: 'cities',
    ownName: 'Ciudad',
    ownNamePlural: 'Ciudades',
    id: {
      name: 'id',
      label: '#',
      field: 'cities.id',
      type: 'pk',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    name: {
      name: 'name',
      label: 'Nombre',
      field: 'cities.name',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    latitude: {
      name: 'latitude',
      label: 'Latitud',
      field: 'cities.latitude',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    longitude: {
      name: 'longitude',
      label: 'Longitud',
      field: 'cities.longitude',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    country_id: {
      name: 'country_id',
      label: 'Pa\u00eds #',
      field: 'cities.country_id',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    region_id: {
      name: 'region_id',
      label: 'Region #',
      field: 'cities.region_id',
      type: 'number',
      allowSearch: true,
      allowExport: true,
      allowImport: true,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    countryName: {
      name: 'countryName',
      label: 'Pa\u00eds',
      field: 'countryName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
    regionName: {
      name: 'regionName',
      label: 'Region',
      field: 'regionName',
      type: 'string',
      allowSearch: true,
      allowExport: true,
      allowImport: false,
      allowInList: true,
      hidden: false,
      sorting: true,
      fixed: false,
    } as DBType,
  },
}

// console.log('labels', JSON.stringify(l.getLabels(l)))
